### ISSUE TITLE
Broken entry saved to database if graphics compo entry file is not a valid image

### ISSUE THREAD

**Issue by teistiz** [Instanssi/Instanssi.org#101]
To reproduce:
- Create a graphics/art compo (= automatic thumbnails from entry files).
- Either allow non-image formats, or make an invalid image file
- Submit the file as an entry to the compo

The entry ends up in the database, but the endpoint returns 500 Internal Server Error.
Trying to GET /api/v1/user_entries/ afterwards also logs an error and returns 500 ISE.

**Comment by katajakasa** [comment]
Due to django-imagekit trying to convert files automatically.
