### ISSUE TITLE
Exporting entries as a ZIP

### ISSUE THREAD

**Issue by katajakasa** [Instanssi/Instanssi.org#290]
required: https://github.com/Instanssi/Instanssi.org/issues/289

1. Make an async entrypoint that allows streaming out zip data. Read files and write them to zipper (or tar.gz) as they get read. Perhaps put them into a directory by compo name too ?
2. Rename files so that they have the list-index as the first part of the name, so that windows/gnome/etc. sort algorithm can sort them out (e.g. <index>-<creator>-<name>.<ext>.

**Comment by zertap** [comment]
Dupe of #65 (and maybe #81) ?

**Comment by katajakasa** [comment]
Closing as dupe
