### ISSUE TITLE
Shirt size requirement when ordering t-shirts

### ISSUE THREAD

**Issue by BFlorry** [Instanssi/Instanssi.org#58]
It could be mandatory to input a clothing size when ordering a t-shirt from the online store. There should be an integer of each size ordered in the management-section so that there would be no manual counting from individual orders.

This helps with pre-ordering the shirts.

**Comment by teistiz** [comment]
Store part is basically implemented now. Will probably add management tools for counting ordered variants later.

**Comment by katajakasa** [comment]
All done, closing.
