### ISSUE TITLE
New kompomaatti

### ISSUE THREAD

**Issue by katajakasa** [Instanssi/Instanssi.org#69]
Same base as webshop (vue.js).

Other things:
- New voting system
- Better navigation, less redundancy in content
- Easily navigable on smaller displays, mobile devices
- Rething voting system ?

**Comment by zouppen** [comment]
Voting method could be the same (sort entries from best to worst) but the algirithm would be STV or other transferrable voting scheme. I can take a look into it. But that affects only the backend. Frontend needs some facelift, too.

**Comment by katajakasa** [comment]
Closing as done.
