### ISSUE TITLE
Commenting for entries?

### ISSUE THREAD

**Issue by teistiz** [Instanssi/Instanssi.org#83]
During Instanssi 2018, some visitors commented that it would be nice if they could leave comments on entries.

Offering the feature publicly would probably be a disaster, but maybe signed in visitors could be allowed to leave greetings.

**Comment by katajakasa** [comment]
I don't think it's a good idea. We would need to moderate the comments, and there are forums to do this commenting anyways -- imo this is not required. Closing.
